# LLM Inference

In [8]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel
import torch

In [9]:
DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"

print(DEVICE)

mps


In [66]:
from transformers import AutoModel

# Initialize the model
model = AutoModel.from_pretrained('jinaai/jina-clip-v1', trust_remote_code=True)

In [94]:
# New meaningful sentences
sentences = ["this is a photo of cats", "this is a photo of dogs"]
sentences = ['A blue cat', 'A red cat']

# Public image URLs
images = ['./cats.jpg']
images = [
    'https://i.pinimg.com/600x315/21/48/7e/21487e8e0970dd366dafaed6ab25d8d8.jpg',
    'https://i.pinimg.com/736x/c9/f2/3e/c9f23e212529f13f19bad5602d84b78b.jpg'
]

In [95]:
truncate_dim = 512

# Encode text and images
text_embeddings = model.encode_text(sentences,
                                    # truncate_dim=truncate_dim, 
                                    # normalize_embeddings=True
                                   )
image_embeddings = model.encode_image(
    images,
    # truncate_dim=truncate_dim,
    # normalize_embeddings=True
)

In [96]:
import numpy as np

def softmax(x):
    return(np.exp(x)/np.exp(x).sum())

In [98]:
np.matmul(text_embeddings, image_embeddings.T)

array([[0.29071358, 0.05689978],
       [0.12780233, 0.29157525]], dtype=float32)

In [101]:
softmax(np.matmul(text_embeddings, image_embeddings.T).T)

array([[0.27457157, 0.23329428],
       [0.21732593, 0.27480826]], dtype=float32)

In [45]:
text_embeddings

array([[-0.1352822 ,  0.04169303,  0.05958096, ...,  0.03613621,
         0.02080175,  0.00599309],
       [-0.09709381, -0.00374282, -0.03742085, ...,  0.01427481,
         0.0357096 , -0.01827639]], shape=(2, 512), dtype=float32)

In [46]:
image_embeddings

array([ 5.65580558e-03,  1.03074878e-01, -3.40717249e-02,  1.07741021e-01,
        3.00849341e-02,  4.10550609e-02, -6.21250235e-02, -2.76538767e-02,
       -5.66998050e-02,  3.28176357e-02,  7.37224519e-02, -2.36659106e-02,
       -1.39976025e-01,  5.32315448e-02, -2.64433213e-02,  1.31805792e-01,
        1.11560049e-02,  1.33657247e-01,  5.81247807e-02, -4.43353169e-02,
       -7.73518756e-02, -3.99740897e-02,  4.41878922e-02, -1.13537788e-01,
        1.34383500e-01, -1.45269513e-01, -2.52276342e-02,  4.37926985e-02,
       -5.81952371e-02,  1.61583096e-01, -6.08372241e-02, -2.61915606e-02,
        1.21249352e-03, -2.37429470e-01, -1.08846202e-01,  9.57844555e-02,
       -5.08496128e-02, -6.14304505e-02,  1.93413384e-02,  1.23099312e-01,
        9.21819732e-03,  7.88313523e-02,  9.78529453e-02, -1.17411643e-01,
       -2.67662015e-02,  9.07308795e-03,  3.54551189e-02, -1.62499830e-01,
        3.24027874e-02, -5.61191561e-03, -1.00332305e-01,  4.27052937e-02,
       -6.32279590e-02, -

In [51]:
model = CLIPModel.from_pretrained("openai/clip-vit-large-patch14").to(DEVICE)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-large-patch14", use_fast=False)

In [52]:
processor.tokenizer.model_max_length

77

In [53]:
import os

os.listdir('.')

['cats.jpg', 'figures', '.ipynb_checkpoints', 'sandbox.ipynb', 'app.log']

In [54]:
# url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open('./cats.jpg')
# image

In [55]:
model

CLIPModel(
  (text_model): CLIPTextTransformer(
    (embeddings): CLIPTextEmbeddings(
      (token_embedding): Embedding(49408, 768)
      (position_embedding): Embedding(77, 768)
    )
    (encoder): CLIPEncoder(
      (layers): ModuleList(
        (0-11): 12 x CLIPEncoderLayer(
          (self_attn): CLIPSdpaAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (layer_norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): CLIPMLP(
            (activation_fn): QuickGELUActivation()
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
          )
          (layer_norm2): LayerNorm((768,), eps=1e

In [56]:
model.text_model

CLIPTextTransformer(
  (embeddings): CLIPTextEmbeddings(
    (token_embedding): Embedding(49408, 768)
    (position_embedding): Embedding(77, 768)
  )
  (encoder): CLIPEncoder(
    (layers): ModuleList(
      (0-11): 12 x CLIPEncoderLayer(
        (self_attn): CLIPSdpaAttention(
          (k_proj): Linear(in_features=768, out_features=768, bias=True)
          (v_proj): Linear(in_features=768, out_features=768, bias=True)
          (q_proj): Linear(in_features=768, out_features=768, bias=True)
          (out_proj): Linear(in_features=768, out_features=768, bias=True)
        )
        (layer_norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): CLIPMLP(
          (activation_fn): QuickGELUActivation()
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
        )
        (layer_norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (final_layer_norm

In [57]:
model.text_projection

Linear(in_features=768, out_features=768, bias=False)

In [58]:
with torch.no_grad():
    inputs = processor(text=["a photo of a cat", "a photo of a dog"], return_tensors="pt", padding=True).to(DEVICE)
    outputs_text = model.text_projection(model.text_model(**inputs).pooler_output)

    inputs = processor(images=image, return_tensors="pt", padding=True).to(DEVICE)
    outputs_image = model.visual_projection(model.vision_model(**inputs).pooler_output)

    inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True).to(DEVICE)
    outputs = model(**inputs)

In [59]:
outputs_text

tensor([[-0.0553,  0.0492,  0.5154,  ...,  0.4025,  0.1555,  0.2346],
        [ 0.1627, -0.0700,  0.3643,  ...,  0.5557,  0.0457,  0.1955]],
       device='mps:0')

In [60]:
outputs.text_embeds

tensor([[-0.0031,  0.0028,  0.0291,  ...,  0.0227,  0.0088,  0.0132],
        [ 0.0091, -0.0039,  0.0203,  ...,  0.0310,  0.0025,  0.0109]],
       device='mps:0')

In [61]:
torch.matmul(outputs_text, outputs_image.T).softmax(dim=0) 

tensor([[1.0000e+00],
        [3.4962e-11]], device='mps:0')

In [62]:
outputs.logits_per_image.softmax(dim=1)

tensor([[9.9925e-01, 7.5487e-04]], device='mps:0')

In [63]:
logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities

print(probs)

tensor([[9.9925e-01, 7.5487e-04]], device='mps:0')


In [ ]:
import torch
from transformers import AutoModelForVision2Seq, AutoProcessor

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DEVICE = "mps" if torch.backends.mps.is_available() else DEVICE

# attention_type = "flash_attention_2" if DEVICE == "cuda" else "eager"
# processor = AutoProcessor.from_pretrained("HuggingFaceTB/SmolVLM-Instruct")
# model = AutoModelForVision2Seq.from_pretrained("HuggingFaceTB/SmolVLM-Instruct",
#                                                torch_dtype=torch.bfloat16,
#                                                _attn_implementation=attention_type).to(DEVICE)

# model_path = 'HuggingFaceTB/SmolVLM-Instruct'
# quant_path = 'qwen-instruct-v0.2-awq'
# quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }
#
# # Загружаем модель
# model = AutoAWQForCausalLM.from_pretrained(
#     model_path, **{"low_cpu_mem_usage": True, "use_cache": False}
# )
# tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
#
# # Квантизация
# model.quantize(tokenizer, quant_config=quant_config)
#
# # Сохраняем квантованную модель
# model.save_quantized(quant_path)
# tokenizer.save_pretrained(quant_path)

# Paper Processor pipeline

In [1]:
import sys
import os

sys.path.append('..')

In [2]:
from src.services.file_processor.client import PaperProcessor

In [3]:
pp = PaperProcessor()

2025-04-21 17:55:26,847 - paper_bot - INFO - Loading model
2025-04-21 17:55:28,605 - paper_bot - INFO - Loading pretrained summarizer


Device set to use mps


In [4]:
await pp.process('2307.00651v1')

2025-04-21 17:55:39,682 - paper_bot - INFO - PDF elements extraction 2307.00651v1
2025-04-21 17:56:05,872 - paper_bot - DEBUG - PDF elements extracted. Raw elements: 11
2025-04-21 17:56:05,873 - paper_bot - INFO - Starting categorizing elements...
2025-04-21 17:56:05,874 - paper_bot - DEBUG - PDF elements extracted. Text: 11. Tables: 0


Token indices sequence length is longer than the specified maximum sequence length for this model (951 > 512). Running this sequence through the model will result in indexing errors


2025-04-21 17:57:13,848 - paper_bot - DEBUG - Adding texts: 15
2025-04-21 17:57:13,849 - paper_bot - DEBUG - Adding text summaries: 15
2025-04-21 17:57:13,850 - paper_bot - DEBUG - Adding summaries: SSL is now a serious competitor for supervised learning, even though it does not require data annotation . There is no clear consensus on whether maximizing or minimizing the mutual information between representations of augmentation views practically contribute to improvement or degradation in performance of SSL models . This paper is a fundamen- tal work where, we investigate role of mutual information in SSL .
2025-04-21 17:57:13,850 - paper_bot - DEBUG - Docs: 15


In [5]:
# def get_all_documents(retriever):
#     """
#     Retrieve all documents stored in the MultiVectorRetriever.

#     Args:
#         retriever: An instance of MultiVectorRetriever.

#     Returns:
#         List[Dict]: A list of dictionaries containing document IDs and their content.
#     """
#     # Fetch all document IDs from the vector store
#     doc_ids = retriever.vectorstore.get(include=["embeddings"])["ids"]

#     # Retrieve documents from the document store using the IDs
#     documents = []
#     for doc_id in doc_ids:
#         doc_content = retriever.docstore.mget([doc_id])[0]
#         documents.append({"id": doc_id, "content": doc_content})

#     return documents

In [6]:
# get_all_documents(pp.retrievers["2307.00651v1"])

In [7]:
# pp.retrievers["2307.00651v1"].vectorstore.get(ids=['256a39f0-2355-44ab-afb7-702b38da0bca'], include=["documents"])["documents"]

In [8]:
pp.retrievers["2307.00651v1"]#("explain the main method authors proposed in the paper?")

MultiVectorRetriever(vectorstore=<langchain_chroma.vectorstores.Chroma object at 0x30fa234d0>, docstore=<langchain_core.stores.InMemoryStore object at 0x33746cb30>, search_kwargs={})

In [11]:
pp.respond("what is the paper about?", "2307.00651v1")

2025-04-21 18:01:06,339 - paper_bot - DEBUG - Found texts: 4
Question: what is the paper about?
Retrieved Context:
Document 1:
Content: In this paper, we assess how this whitening process un- wittingly eliminates the synergistic information along with redundant information . This eventually leads us to reconsider the problem of mutual information between two variables (two views and the target representation) This leads to a larger controversy on how mutual information relates to learning the target rep- resentation .
--------------------------------------------------
Document 2:
Content: In its simplest form, suppose we have two source variables S1 and S2 carrying joint mutual information I(T;S1,S2) about a target variable T . Hence each of the source variables has mutual information with the target variable . The joint information between sources and target could be decomposed as three elements, unique, redundant, and synergistic information . This contrast in essence creates an info

'The paper is about assessing how the whitening process un-wittingly eliminates synergistic information along with redundant information, which eventually leads to a larger controversy on how mutual information relates to learning the target representation.'

In [10]:
from src.services.vlm.client import CustomLLM

In [ ]:
llm = CustomLLM()
q_and_context = {
    "context": {"texts": ["no information found"], "images": []},
    "question": "what does the world look like today?",
}

In [5]:
processed = llm.preprocess_input(q_and_context)

2025-04-21 16:25:55,812 - paper_bot - INFO - Formatted texts: 20


In [12]:
l = len(processed['input_ids'][0])
l

38

In [8]:
inputs = {k: v.to(llm.device) for k, v in processed.items()}

In [6]:
processed

{'input_ids': tensor([[    1, 11126,    42,  2988,  2914,  1962,    42,   732,  1072,   260,
           905,  1492,   702,  1834,    47,   198,   198, 11247,  1015, 44339,
          1096,   281,  1694,   284,  2272,   355,  8158,  2441,    42,   198,
          4607,  1096,   983, 49154,   198,  9519,  9531,    42]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [14]:
generated_ids = llm.model.generate(**inputs, max_new_tokens=128, )

In [16]:
generated_ids.shape

torch.Size([1, 61])

In [23]:
mod_gen_id = generated_ids[0][l:].reshape(1, -1)

In [24]:
generated_texts = llm.processor.batch_decode(
    mod_gen_id,
    skip_special_tokens=True,
)

In [27]:
generated_texts[0].strip()

'The world today is a place where people live in different countries, speak different languages, and have different cultures.'

In [9]:
import torch
from transformers import pipeline

In [11]:
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
summarizer = pipeline("summarization", model="Falconsai/text_summarization", device=device)

Device set to use mps


In [12]:
texts = [
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
    'SSL frameworks consist of two key elements, namely, loss function, and pretext task [8] This type of baselines suffer from the problem of potential representation collapse, as well as the need for large negative batches for effective representation . Next generation baselines emerged as non-contrastive or negative pair-free baselines [13, 14], essentially eliminating the need to contrast against negative views (negative pairs), and almost with no risk of representation collapse .',
]

In [14]:
texts_summaries = summarizer(
                texts,  # List of input texts
                max_length=500,  # Maximum length of the summary
                min_length=25,  # Minimum length of the summary
                do_sample=False,  # Use deterministic summarization
                batch_size=4  # Number of texts processed in parallel
            )

Your max_length is set to 500, but your input_length is only 101. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 500, but your input_length is only 101. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)


In [16]:
len(texts_summaries), len(texts)

(7, 7)

In [17]:
texts_summaries

[{'summary_text': 'SSL frameworks consist of two key elements: loss function and pretext task . Next generation baselines emerged as non-contrastive or negative pair-free baselines . This type of baselines suffer from the problem of potential representation collapse .'},
 {'summary_text': 'SSL frameworks consist of two key elements: loss function and pretext task . Next generation baselines emerged as non-contrastive or negative pair-free baselines . This type of baselines suffer from the problem of potential representation collapse .'},
 {'summary_text': 'SSL frameworks consist of two key elements: loss function and pretext task . Next generation baselines emerged as non-contrastive or negative pair-free baselines . This type of baselines suffer from the problem of potential representation collapse .'},
 {'summary_text': 'SSL frameworks consist of two key elements: loss function and pretext task . Next generation baselines emerged as non-contrastive or negative pair-free baselines . T